name: Finding
description: Report a pentest finding / vulnerability
title: "[Finding]: "
labels: ["Finding"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A short summary of the issue.
  - type: textarea
    id: technicalDescription
    attributes:
      label: Technical Description
      description: Technical Description of the finding and supporting materials like steps to reproduce.
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What is the impact of the vulnerability?
      placeholder: An adversary can ...
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: What severity does the vulnerability have towards the threat model?
      options:
        - Low
        - Moderate
        - Elevated
        - High
        - Extreme
    validations:
      required: true
  - type: input
    id: type
    attributes:
      label: Vulnerability Type
      description: What is the finding type or [CWE](https://cwe.mitre.org/)?
      placeholder: ex. Remote Code Execution
    validations:
      required: false